# Generated by Django 6.0.4 on 2026-05-06 16:28

import bboard.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bboard', '0001_initial'), ('bboard', '0002_rubric_alter_bd_options_bd_rubric'), ('bboard', '0003_bd_is_active_bd_kind_alter_bd_content_alter_bd_price_and_more'), ('bboard', '0004_alter_bd_options_alter_bd_kind_and_more'), ('bboard', '0005_alter_bd_options_alter_bd_title')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубкрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'invalid': 'Неправильное название объявления', 'odd': 'Some error', 'unique': 'Объявление с таким имененем уже существует'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4}$'), django.core.validators.MinLengthValidator(bboard.utils.validators.get_min_length), bboard.utils.validators.validate_even], verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубкрика')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли объявление на сайте', verbose_name='Активное')),
                ('kind', models.CharField(choices=[(None, 'Выбкрите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Сдам')], default='s', max_length=1, verbose_name='Тип объявления')),
            ],
            options={
                'ordering': ['-published', 'title'],
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'unique_together': {('published', 'title')},
            },
        ),
    ]
