# Generated by Django 6.0.4 on 2026-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bd_options_bd_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно ли объявление на сайте', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='bd',
            name='kind',
            field=models.CharField(choices=[(None, 'Выбкрите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Сдам')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='bd',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
