# Generated by Django 6.0.4 on 2026-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bd_is_active_bd_kind_alter_bd_content_alter_bd_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Объяаление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bd',
            name='kind',
            field=models.CharField(choices=[(None, 'Выбкрите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Сдам')], default='s', max_length=1, verbose_name='Тип объявления'),
        ),
        migrations.AlterUniqueTogether(
            name='bd',
            unique_together={('published', 'title')},
        ),
    ]
