# Generated by Django 6.0.4 on 2026-05-06 16:22

import bboard.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bd_options_alter_bd_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Неправильное название объявления', 'odd': 'Some error', 'unique': 'Объявление с таким имененем уже существует'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4}$'), django.core.validators.MinLengthValidator(bboard.utils.validators.get_min_length), bboard.utils.validators.validate_even], verbose_name='Название'),
        ),
    ]
