# Generated by Django 6.0.4 on 2026-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_squashed_0005_alter_bd_options_alter_bd_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Неправильное название объявления', 'odd': 'Some error', 'unique': 'Объявление с таким имененем уже существует'}, max_length=50, verbose_name='Название'),
        ),
    ]
